project:
  organism: Xenopus tropicalis
  assay: snRNA-seq
  developmental_series: gastrulation
  annotation_column: region_annotation

qc:
  min_genes_per_cell: 1000
  max_pct_mitochondrial: 20
  max_pct_ribosomal: 3.5
  normalization_target_sum: 10000

differential_expression:
  method: wilcoxon
  minimum_cells_all_group_test: 7
  fdr_max: 0.05
  absolute_log2fc_min: 1.0
  top_n_per_group: 25

datasets:
  - slug: Stage10_5-WT
    stage: Stage10
    condition: WT
    input: data/raw/Stage10/PARSE-WTSt105-Unfiltered_FromSeurat.h5ad
  - slug: Stage11_25-WT
    stage: Stage11.25
    condition: WT
    input: data/raw/Stage11_25/PARSE-WTSt1125-Unfiltered_FromSeurat.h5ad
  - slug: Stage11_25-MO
    stage: Stage11.25
    condition: MO
    input: data/raw/Stage11_25/PARSE-MOSt1125-Unfiltered_FromSeurat.h5ad
  - slug: Stage12_0-WT
    stage: Stage12.0
    condition: WT
    input: data/raw/Stage12_0/PARSE-WTSt12-Unfiltered_FromSeurat.h5ad
  - slug: Stage12_0-MO
    stage: Stage12.0
    condition: MO
    input: data/raw/Stage12_0/PARSE-MOSt12-Unfiltered_FromSeurat.h5ad
  - slug: Stage12_5-WT
    stage: Stage12.5
    condition: WT
    input: data/raw/Stage12_5/PARSE-WTSt12_5-Unfiltered_FromSeurat.h5ad
  - slug: Stage13-WT
    stage: Stage13
    condition: WT
    input: data/raw/Stage13/PARSE-WTSt13-Unfiltered_FromSeurat.h5ad
