def assign_marker_based_labels(adata, marker_dict, threshold=0.5):
    ...

def smooth_labels_by_neighbors(adata, label_column, n_neighbors=20):
    ...

def export_annotation_counts(adata, label_column, output_path):
    ...
