def label_mito_ribo_genes(adata):
    ...

def calculate_qc_metrics(adata):
    ...

def export_qc_summary(adata, output_path):
    ...

def run_scrublet(adata):
    ...

def remove_predicted_doublets(adata):
    ...
